# -*- coding: utf-8 -*-
"""ShwetaMLProjectEDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19UGKvXqr65PCrVe0mi8hFBmxZG6oHSQZ

#  What Is Market Segmentation? 
Market segmentation is a marketing term that refers to aggregating prospective buyers into groups or segments with common needs and who respond similarly to a marketing action.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

from google.colab import files
 
 
uploaded = files.upload()

import io
 
df = pd.read_csv(io.BytesIO(uploaded['Customer Data.csv']))
print(df)

df.head()

df.tail()

"""# EDA"""

df.shape

df.info()

df.describe()

df.isnull().sum()

df['MINIMUM_PAYMENTS']=df["MINIMUM_PAYMENTS"].fillna(df["MINIMUM_PAYMENTS"].mean())

df['CREDIT_LIMIT']=df["CREDIT_LIMIT"].fillna(df["CREDIT_LIMIT"].mean())

df.isnull().sum()

df.drop("CUST_ID",axis=1,inplace=True)

df.columns

plt.figure(figsize=(15,15))
sns.heatmap(df.corr(),annot=True,cmap="viridis")

columns=df.select_dtypes("int64")
for i in columns:
    plt.figure(figsize=(20,10))
    sns.countplot(data=df,x=i)
    plt.xticks(rotation=90)
    plt.show()

pip install scipy

from scipy.stats import skew

for i in df:
    sns.distplot(df[i])
    plt.show()
    print(skew(df[i]))

plt.figure(figsize=(15,8))
plt.suptitle("Visualizing the Skewness",fontsize=20)
ptno=1
for i in df:
    if ptno<=13:
        ax=plt.subplot(4,4,ptno)
        sns.distplot(df[i],color="navy")
        plt.xlabel(i,fontsize=14)
    ptno+=1
plt.tight_layout()

sns.pairplot(df)

plt.figure(figsize=(15,10))
plt.suptitle("Visualizing the distribution",fontsize=20)
ptno=1
for i in df:
    if ptno<=13:
        ax=plt.subplot(4,4,ptno)
        sns.boxplot(df[i],color="yellow")
        plt.xlabel(i,fontsize=14)
    ptno+=1
plt.tight_layout()

!pip install pandas-profiling

import pandas_profiling as pp

pp.ProfileReport(df)



